name: Report Treesitter capture bug
description: Report a case where the treesitter capture is incomplete
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Before** reporting an issue, make sure to read the documentation and search existing issues. Usage questions such as ***"How do I...?"*** belong in Discussions and will be closed.
  - type: checkboxes
    attributes:
      label: Did you check docs and existing issues?
      description: Make sure you checked all of the below before submitting an issue
      options:
        - label: I have searched the existing issues
          required: true
        - label: I have searched the existing issues of plugins related to this issue
          required: true
  - type: input
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "0.8.0 commit db1b0ee3b30f"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "MacOS 11.5"
    validations:
      required: true
  - type: textarea
    attributes:
      label: The input text
      description: "The buffer content before the logging action. Use | to indicate the cursor position. e.g: `local foo = \"ba|r\"` means the cursor position is at the `a` letter."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actions performed
      description: "One or more actions performed on the input text. e.g: insert_log_below, insert_log_above, insert_plain_log_below, insert_plain_log_above, insert_batch_log, add_log_targets_to_batch, ..."
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected output text
      description: The expected buffer content after the loggin action.
    validations:
      required: true
